package it.akademija.audit;

public enum AuditActionEnum {
    CREATE_NEW_USER,
    CREATE_NEW_USERGROUP,
    CREATE_NEW_DOCUMENT,
    CREATE_NEW_DOCUMENT_TYPE,
    MODIFY_USER,
    MODIFY_USERGROUP,
    MODIFY_DOCUMENT_TYPE,
    DELETE_USERGROUP,
    DELETE_DOCUMENT_TYPE,
    APPROVE_DOCUMENT,
    REJECT_DOCUMENT,
    SUBMIT_DOCUMENT,
    SUSPEND_USER,
    REMOVE_USER_FROM_GROUP,
    ADD_USER_TO_GROUP,
}
